services:
  app-counter:
    depends_on:
      - db-counter
    container_name: application
    image: 'ghcr.io/ziryt/counter-app:latest'
    build:
      dockerfile: Dockerfile
    environment:
      - LOGGING_LEVEL_COM_ZIRYT=INFO
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/counter
      - SPRING_DATASOURCE_USERNAME=ziryt
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_INITIALIZATION_MODE=always
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    volumes:
      - vol1:/data/app
    ports:
      - "8080:8080"
    networks:
      - net1
    restart: unless-stopped

  db-counter:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: counter
      POSTGRES_USER: ziryt
      POSTGRES_PASSWORD: 123456
      PGDATA: data/postgres
    volumes:
      - vol1:/data
    ports:
      - "5332:5432"
    networks:
      - net1
    restart: unless-stopped

networks:
  net1:
    driver: bridge

volumes:
  vol1: