services:
  app-counter:
    depends_on:
      - db-counter
    container_name: application
    image: 'docker-spring-boot-postgres:latest'
    build:
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5332/counter
      - SPRING_DATASOURCE_USERNAME=ziryt
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    volumes:
      - vol1:/data/app
    ports:
      - "8080:8080"
    networks:
      - net1
    restart: unless-stopped

  db-counter:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ziryt
      POSTGRES_PASSWORD: 123456
      PGDATA: data/postgres
    volumes:
      - vol1:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - net1
    restart: unless-stopped

networks:
  net1:
    driver: bridge

volumes:
  vol1: