name: Update docker image on push

on:
  push

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: |
          docker login --username ziryt --password ${{secrets.GH_PAT}}

      - name: Build
        run: |
          docker build . --tag ghcr.io/ziryt/counter-app:latest

      - name: Build
        run: |
          docker push ghcr.io/ziryt/counter-app:latest